"""Molecule test generation agent.

Creates molecule test files (converge.yml, verify.yml) for generated Ansible roles.
Static files (molecule.yml, create.yml, destroy.yml) are created deterministically;
dynamic files are generated by an LLM using pre-flight checks from the migration plan.
"""

from collections.abc import Callable
from pathlib import Path
from typing import ClassVar, Literal

from langchain_community.tools.file_management.list_dir import ListDirectoryTool
from langchain_community.tools.file_management.read import ReadFileTool
from langchain_community.tools.file_management.write import WriteFileTool
from langchain_core.tools import BaseTool
from langgraph.graph import START, StateGraph

from prompts.get_prompt import get_prompt
from src.exporters.agent_state import MoleculeAgentState
from src.exporters.export_agent import ExportAgent
from src.exporters.state import ExportState
from src.model import get_runnable_config
from src.types import ChecklistStatus
from src.types.telemetry import AgentMetrics
from src.utils.logging import get_logger

logger = get_logger(__name__)

# Molecule files that are created deterministically (no LLM needed)
STATIC_MOLECULE_FILES = {"molecule.yml", "create.yml", "destroy.yml"}

# Molecule files that require LLM generation
DYNAMIC_MOLECULE_FILES = {"converge.yml", "verify.yml"}


class MoleculeAgent(ExportAgent[ExportState]):
    """Agent responsible for generating molecule test files.

    This agent runs after the WriteAgent and before the ValidationAgent.
    It creates molecule test scenarios in two phases:
    1. Static scaffold: deterministic files (molecule.yml, create.yml, destroy.yml)
    2. Dynamic generation: LLM-generated files (converge.yml, verify.yml) using
       pre-flight checks from the migration plan

    Molecule test generation is non-fatal — failures are logged but do not
    block the migration pipeline.
    """

    _NAME = "Molecule Test Generator"

    BASE_TOOLS: ClassVar[list[Callable[[], BaseTool]]] = [
        lambda: ReadFileTool(),
        lambda: WriteFileTool(),
        lambda: ListDirectoryTool(),
    ]

    SYSTEM_PROMPT_NAME = "export_ansible_molecule_system"
    USER_PROMPT_NAME = "export_ansible_molecule_task"

    def __init__(self, model=None):
        super().__init__(model)
        self.max_attempts = 3
        self._graph = self._build_internal_graph()
        self._current_metrics: AgentMetrics | None = None

    def extra_tools_from_state(self, state: ExportState) -> list[BaseTool]:
        if state.checklist is None:
            return []
        return state.checklist.get_tools()

    def _build_internal_graph(self):
        """Build the internal StateGraph for molecule test generation."""
        workflow = StateGraph(MoleculeAgentState)
        workflow.add_node("scaffold_static_files", self._scaffold_static_files_node)
        workflow.add_node("write_dynamic_files", self._write_dynamic_files_node)
        workflow.add_node("check_files", self._check_files_node)

        workflow.add_edge(START, "scaffold_static_files")
        workflow.add_edge("scaffold_static_files", "write_dynamic_files")
        workflow.add_edge("write_dynamic_files", "check_files")
        workflow.add_conditional_edges("check_files", self._evaluate_node)

        return workflow.compile()

    def _create_molecule_scaffold(self, ansible_path: Path, role_name: str) -> None:
        """Generate Molecule configuration files deterministically.

        Args:
            ansible_path: Path to the Ansible role directory
            role_name: Name of the role
        """
        molecule_dir = ansible_path / "molecule" / "default"
        molecule_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Regenerating Molecule files for {role_name}")

        # Generate molecule.yml — delegated driver for AAP/OpenShift
        molecule_config = """---
driver:
  name: default

platforms:
  - name: molecule-test-instance
    groups:
      - all

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../"
  inventory:
    hosts:
      all:
        hosts:
          molecule-test-instance:
            ansible_connection: local

verifier:
  name: ansible
"""
        (molecule_dir / "molecule.yml").write_text(molecule_config)

        # Generate converge.yml — container-safe, no include_role, no become
        # All paths use /tmp/molecule_test/ prefix. WriteAgent generates the real one.
        converge_playbook = f"""---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Placeholder — WriteAgent generates container-safe converge
      ansible.builtin.debug:
        msg: "Role {role_name} converge placeholder — use /tmp/molecule_test/ paths"
"""
        (molecule_dir / "converge.yml").write_text(converge_playbook)

        # Generate no-op create.yml and destroy.yml for delegated driver
        for playbook_name in ("create", "destroy"):
            noop_playbook = f"""---
- name: {playbook_name.capitalize()}
  hosts: localhost
  connection: local
  gather_facts: false
  tasks: []
"""
            (molecule_dir / f"{playbook_name}.yml").write_text(noop_playbook)

        # Generate verify.yml placeholder — WriteAgent generates the real one
        verify_playbook = f"""---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify role {role_name} executed successfully
      ansible.builtin.debug:
        msg: "Role {role_name} applied successfully"
"""
        (molecule_dir / "verify.yml").write_text(verify_playbook)

        logger.info(f"Generated Molecule files in {molecule_dir}")

    def _scaffold_static_files_node(
        self, state: MoleculeAgentState
    ) -> MoleculeAgentState:
        """Create static molecule files deterministically (no LLM)."""
        export_state = state.export_state
        slog = logger.bind(phase="scaffold_static_files")
        slog.info("Creating static molecule files")

        ansible_path = Path(export_state.get_ansible_path())
        role_name = str(export_state.module)

        # Create molecule scaffold
        self._create_molecule_scaffold(ansible_path, role_name)

        # Mark static files as complete in checklist
        if export_state.checklist is not None:
            molecule_dir = ansible_path / "molecule" / "default"
            for filename in STATIC_MOLECULE_FILES:
                target_path = str(molecule_dir / filename)
                updated = export_state.checklist.update_task(
                    source_path="N/A",
                    target_path=target_path,
                    status=ChecklistStatus.COMPLETE,
                    notes="Created by MoleculeAgent (deterministic scaffold)",
                )
                if not updated:
                    slog.debug(f"Checklist item not found for {target_path}, skipping")
            export_state.checklist.save(export_state.get_checklist_path())

        slog.info("Static molecule files created successfully")
        state.export_state = export_state
        return state

    def _write_dynamic_files_node(
        self, state: MoleculeAgentState
    ) -> MoleculeAgentState:
        """Generate converge.yml and verify.yml using LLM agent."""
        export_state = state.export_state
        slog = logger.bind(phase="write_dynamic_files", attempt=state.attempt)
        slog.info("Generating dynamic molecule files (converge.yml, verify.yml)")

        ansible_path = export_state.get_ansible_path()

        system_message = str(get_prompt(self.SYSTEM_PROMPT_NAME))
        user_prompt = str(
            get_prompt(self.USER_PROMPT_NAME).format(
                module=export_state.module,
                ansible_path=ansible_path,
                high_level_migration_plan=export_state.high_level_migration_plan,
                migration_plan=export_state.module_migration_plan.to_document(),
                checklist=(
                    export_state.checklist.to_markdown()
                    if export_state.checklist
                    else ""
                ),
            )
        )

        result = self.invoke_react(
            export_state,
            [
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_prompt},
            ],
            self._current_metrics,
        )

        if export_state.checklist is not None:
            export_state.checklist.save(export_state.get_checklist_path())

        message = self.get_last_ai_message(result)
        if message:
            slog.info("Dynamic molecule file generation completed")
        else:
            slog.warning("Molecule agent did not produce output")

        state.export_state = export_state
        state.last_result = result
        state.attempt += 1
        return state

    def _check_files_node(self, state: MoleculeAgentState) -> MoleculeAgentState:
        """Verify all molecule files exist on disk."""
        export_state = state.export_state
        slog = logger.bind(phase="check_files", attempt=state.attempt)

        ansible_path = Path(export_state.get_ansible_path())
        molecule_dir = ansible_path / "molecule" / "default"

        all_files = STATIC_MOLECULE_FILES | DYNAMIC_MOLECULE_FILES
        missing = [
            str(molecule_dir / f) for f in all_files if not (molecule_dir / f).exists()
        ]

        if missing:
            slog.warning(f"Missing {len(missing)} molecule files: {missing}")
            state.missing_files = missing
            state.complete = False
        else:
            slog.info("All molecule files created successfully")
            state.missing_files = []
            state.complete = True

        return state

    def _evaluate_node(
        self, state: MoleculeAgentState
    ) -> Literal["write_dynamic_files", "__end__"]:
        """Decide whether to retry or finish."""
        if state.complete:
            return "__end__"
        if state.attempt >= state.max_attempts:
            logger.warning(
                f"Molecule agent: max attempts ({state.max_attempts}) reached, "
                f"missing files: {state.missing_files}"
            )
            return "__end__"
        return "write_dynamic_files"

    def execute(self, state: ExportState, metrics: AgentMetrics | None) -> ExportState:
        """Execute molecule test generation workflow.

        This is non-fatal — any exception is caught and logged as a warning.
        The pipeline continues regardless of molecule test generation outcome.
        """
        self._log.info("Starting molecule agent workflow")
        state = state.update(current_phase="molecule_testing")

        # Store metrics reference for internal nodes
        self._current_metrics = metrics

        # Check if role has molecule items in checklist
        if state.checklist is None:
            self._log.info("No checklist, skipping molecule agent")
            self._current_metrics = None
            return state

        has_molecule_items = bool(
            state.checklist.items_by_category(include={"molecule"})
        )
        if not has_molecule_items:
            self._log.info("No molecule items in checklist, skipping")
            self._current_metrics = None
            return state

        try:
            internal_state = MoleculeAgentState(
                export_state=state,
                attempt=0,
                max_attempts=self.max_attempts,
                complete=False,
            )

            final_state_dict = self._graph.invoke(internal_state, get_runnable_config())
            final_state = MoleculeAgentState(**final_state_dict)

            if metrics:
                metrics.record_metric("attempts", final_state.attempt)
                metrics.record_metric("complete", final_state.complete)
                if final_state.missing_files:
                    metrics.record_metric(
                        "missing_files", len(final_state.missing_files)
                    )

            self._log.info(
                f"Molecule agent finished: complete={final_state.complete}, "
                f"attempts={final_state.attempt}/{self.max_attempts}"
            )
            self._current_metrics = None
            return final_state.export_state

        except Exception as e:
            self._log.warning(
                f"Molecule test generation failed (non-fatal): {e}",
                exc_info=True,
            )
            self._current_metrics = None
            return state
