"""Molecule test generation agent.

Creates molecule test files (converge.yml, verify.yml) for generated Ansible roles.
Static files (molecule.yml, create.yml, destroy.yml) are created deterministically;
dynamic files are generated by an LLM using pre-flight checks from the migration plan.
"""

import re
from collections.abc import Callable
from pathlib import Path
from typing import ClassVar, Literal

from langchain_community.tools.file_management.list_dir import ListDirectoryTool
from langchain_community.tools.file_management.read import ReadFileTool
from langchain_community.tools.file_management.write import WriteFileTool
from langchain_core.tools import BaseTool
from langgraph.graph import START, StateGraph

from prompts.get_prompt import get_prompt
from src.base_agent import BaseAgent
from src.exporters.agent_state import MoleculeAgentState
from src.exporters.ansible_molecule import AnsibleMolecule
from src.exporters.state import ExportState
from src.model import get_runnable_config
from src.types import ChecklistStatus
from src.types.telemetry import AgentMetrics
from src.utils.logging import get_logger

logger = get_logger(__name__)

# Molecule files that are created deterministically (no LLM needed)
STATIC_MOLECULE_FILES = {"molecule.yml", "create.yml", "destroy.yml"}

# Molecule files that require LLM generation
DYNAMIC_MOLECULE_FILES = {"converge.yml", "verify.yml"}


def _extract_preflight_checks(migration_plan_text: str) -> str:
    """Extract the pre-flight checks section from a migration plan document.

    Args:
        migration_plan_text: Full text of the migration plan

    Returns:
        The pre-flight checks section content, or a fallback message
    """
    pattern = r"(?:^|\n)##\s*Pre-?flight\s+checks?:?\s*\n(.*?)(?:\n##\s|\Z)"
    match = re.search(pattern, migration_plan_text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return "(No pre-flight checks found in migration plan — generate basic file existence checks based on the role's tasks.)"


class MoleculeAgent(BaseAgent[ExportState]):
    """Agent responsible for generating molecule test files.

    This agent runs after the WriteAgent and before the ValidationAgent.
    It creates molecule test scenarios in two phases:
    1. Static scaffold: deterministic files (molecule.yml, create.yml, destroy.yml)
    2. Dynamic generation: LLM-generated files (converge.yml, verify.yml) using
       pre-flight checks from the migration plan

    Molecule test generation is non-fatal — failures are logged but do not
    block the migration pipeline.
    """

    BASE_TOOLS: ClassVar[list[Callable[[], BaseTool]]] = [
        lambda: ReadFileTool(),
        lambda: WriteFileTool(),
        lambda: ListDirectoryTool(),
    ]

    SYSTEM_PROMPT_NAME = "export_ansible_molecule_system"
    USER_PROMPT_NAME = "export_ansible_molecule_task"

    def __init__(self, model=None):
        super().__init__(model)
        self.max_attempts = 3
        self._graph = self._build_internal_graph()
        self._current_metrics: AgentMetrics | None = None

    def extra_tools_from_state(self, state: ExportState) -> list[BaseTool]:
        if state.checklist is None:
            return []
        return state.checklist.get_tools()

    def _build_internal_graph(self):
        """Build the internal StateGraph for molecule test generation."""
        workflow = StateGraph(MoleculeAgentState)
        workflow.add_node("scaffold_static_files", self._scaffold_static_files_node)
        workflow.add_node("write_dynamic_files", self._write_dynamic_files_node)
        workflow.add_node("check_files", self._check_files_node)

        workflow.add_edge(START, "scaffold_static_files")
        workflow.add_edge("scaffold_static_files", "write_dynamic_files")
        workflow.add_edge("write_dynamic_files", "check_files")
        workflow.add_conditional_edges("check_files", self._evaluate_node)

        return workflow.compile()

    def _scaffold_static_files_node(
        self, state: MoleculeAgentState
    ) -> MoleculeAgentState:
        """Create static molecule files deterministically (no LLM)."""
        export_state = state.export_state
        slog = logger.bind(phase="scaffold_static_files")
        slog.info("Creating static molecule files")

        ansible_path = Path(export_state.get_ansible_path())
        role_name = str(export_state.module)

        # Use AnsibleMolecule's existing scaffold method
        molecule = AnsibleMolecule()
        molecule._setup_molecule_files(ansible_path, role_name, force=True)

        # Mark static files as complete in checklist
        if export_state.checklist is not None:
            molecule_dir = ansible_path / "molecule" / "default"
            for filename in STATIC_MOLECULE_FILES:
                target_path = str(molecule_dir / filename)
                updated = export_state.checklist.update_task(
                    source_path="N/A",
                    target_path=target_path,
                    status=ChecklistStatus.COMPLETE,
                    notes="Created by MoleculeAgent (deterministic scaffold)",
                )
                if not updated:
                    slog.debug(f"Checklist item not found for {target_path}, skipping")
            export_state.checklist.save(export_state.get_checklist_path())

        slog.info("Static molecule files created successfully")
        state.export_state = export_state
        return state

    def _write_dynamic_files_node(
        self, state: MoleculeAgentState
    ) -> MoleculeAgentState:
        """Generate converge.yml and verify.yml using LLM agent."""
        export_state = state.export_state
        slog = logger.bind(phase="write_dynamic_files", attempt=state.attempt)
        slog.info("Generating dynamic molecule files (converge.yml, verify.yml)")

        ansible_path = export_state.get_ansible_path()

        # Extract pre-flight checks from migration plan
        plan_text = export_state.module_migration_plan.to_document()
        preflight_checks = _extract_preflight_checks(plan_text)

        system_message = str(get_prompt(self.SYSTEM_PROMPT_NAME))
        user_prompt = str(
            get_prompt(self.USER_PROMPT_NAME).format(
                module=export_state.module,
                ansible_path=ansible_path,
                preflight_checks=preflight_checks,
                checklist=(
                    export_state.checklist.to_markdown()
                    if export_state.checklist
                    else ""
                ),
            )
        )

        result = self.invoke_react(
            export_state,
            [
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_prompt},
            ],
            self._current_metrics,
        )

        if export_state.checklist is not None:
            export_state.checklist.save(export_state.get_checklist_path())

        message = self.get_last_ai_message(result)
        if message:
            slog.info("Dynamic molecule file generation completed")
        else:
            slog.warning("Molecule agent did not produce output")

        state.export_state = export_state
        state.last_result = result
        state.attempt += 1
        return state

    def _check_files_node(self, state: MoleculeAgentState) -> MoleculeAgentState:
        """Verify all molecule files exist on disk."""
        export_state = state.export_state
        slog = logger.bind(phase="check_files", attempt=state.attempt)

        ansible_path = Path(export_state.get_ansible_path())
        molecule_dir = ansible_path / "molecule" / "default"

        all_files = STATIC_MOLECULE_FILES | DYNAMIC_MOLECULE_FILES
        missing = [
            str(molecule_dir / f) for f in all_files if not (molecule_dir / f).exists()
        ]

        if missing:
            slog.warning(f"Missing {len(missing)} molecule files: {missing}")
            state.missing_files = missing
            state.complete = False
        else:
            slog.info("All molecule files created successfully")
            state.missing_files = []
            state.complete = True

        state.export_state = export_state
        return state

    def _evaluate_node(
        self, state: MoleculeAgentState
    ) -> Literal["write_dynamic_files", "__end__"]:
        """Decide whether to retry or finish."""
        if state.complete:
            return "__end__"
        if state.attempt >= state.max_attempts:
            logger.warning(
                f"Molecule agent: max attempts ({state.max_attempts}) reached, "
                f"missing files: {state.missing_files}"
            )
            return "__end__"
        return "write_dynamic_files"

    def execute(self, state: ExportState, metrics: AgentMetrics | None) -> ExportState:
        """Execute molecule test generation workflow.

        This is non-fatal — any exception is caught and logged as a warning.
        The pipeline continues regardless of molecule test generation outcome.
        """
        self._log.info("Starting molecule agent workflow")
        state = state.update(current_phase="molecule_testing")

        # Store metrics reference for internal nodes
        self._current_metrics = metrics

        # Check if role has molecule items in checklist
        if state.checklist is None:
            self._log.info("No checklist, skipping molecule agent")
            self._current_metrics = None
            return state

        has_molecule_items = any(
            "molecule" in (item.target_path or "").lower()
            for item in state.checklist.items
        )
        if not has_molecule_items:
            self._log.info("No molecule items in checklist, skipping")
            self._current_metrics = None
            return state

        try:
            internal_state = MoleculeAgentState(
                export_state=state,
                attempt=0,
                max_attempts=self.max_attempts,
                complete=False,
            )

            final_state_dict = self._graph.invoke(internal_state, get_runnable_config())
            final_state = MoleculeAgentState(**final_state_dict)

            if metrics:
                metrics.record_metric("attempts", final_state.attempt)
                metrics.record_metric("complete", final_state.complete)
                if final_state.missing_files:
                    metrics.record_metric(
                        "missing_files", len(final_state.missing_files)
                    )

            self._log.info(
                f"Molecule agent finished: complete={final_state.complete}, "
                f"attempts={final_state.attempt}/{self.max_attempts}"
            )
            self._current_metrics = None
            return final_state.export_state

        except Exception as e:
            self._log.warning(
                f"Molecule test generation failed (non-fatal): {e}",
                exc_info=True,
            )
            self._current_metrics = None
            return state
