---
apiVersion: v1
kind: Secret
metadata:
  name: x2a-secrets
  namespace: x2a-convertor
  labels:
    app: x2a-convertor
type: Opaque
stringData:
  # AWS Bedrock Token (recommended)
  # Get from: AWS Console → Bedrock → Model Access
  AWS_BEARER_TOKEN_BEDROCK: "REPLACE_WITH_YOUR_TOKEN"
  
  # OR OpenAI API Key
  # Get from: https://platform.openai.com/api-keys
  # OPENAI_API_KEY: "sk-your-key-here"
  
  # OR for Local/Custom OpenAI-compatible endpoints
  # OPENAI_API_BASE: "http://localhost:11434/v1"
  # OPENAI_API_KEY: "not-needed"
  
  # Optional: LangChain API Key (for tracing)
  # LANGCHAIN_API_KEY: "ls-your-key-here"
  # LANGCHAIN_PROJECT: "x2a-production"

---
# Instructions for creating this secret:
# 
# Method 1: Using oc command (recommended for production)
# oc create secret generic x2a-secrets \
#   --from-literal=AWS_BEARER_TOKEN_BEDROCK='your-actual-token' \
#   -n x2a-convertor
#
# Method 2: Using this file (for testing only)
# Replace REPLACE_WITH_YOUR_TOKEN above and run:
# oc apply -f openshift/secret.yaml
#
# Security Note: Never commit real credentials to git!

